name: Job Hunter AI

on:
  workflow_dispatch:

  schedule:
    - cron: "0 */6 * * *"

permissions:
  contents: write

jobs:
  run-job-hunter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Run Job Hunter AI
        run: |
          python -m job_hunter_ai.main

      - name: Commit updated files
        run: |
          git config --global user.name "aly-abbas11"
          git config --global user.email "176041272+aly-abbas11@users.noreply.github.com"

          git add .

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Auto update jobs"
          fi

      - name: Push changes
        run: |
          git push